### ISSUE TITLE
Push cruzado

### ISSUE THREAD

**Issue by ramon-bernardo** [moviebr/baiakthunder#16]
Encontrei seu projeto esses dias e hoje comparei com o meu, notei que o push cruzado está em `Game::playerMoveCreature()` e não em `Game::playerMove()`. Aparentemente vai funcionar apenas com criatura.

**Comment by moviebr** [comment]
Não conheço muito da ferramenta do push cruzado, caso tenha mais informações sobre como ele funciona, gostaria de saber, porque, até então onde eu sei o push cruzado é utilizado somente em criaturas.

**Comment by ramon-bernardo** [comment]
Eu também tive o interesse em adicionar o push em minha source, os jogadores usam bastante no PvP.
Aqui tem um [link](https://tibiaking.com/forums/topic/97003-tutorial-push-cruzado-e-sua-hist%C3%B3ria/) para a história e como adicionar. Eu nunca utilizei em criaturas, por isso acabei notando.

**Comment by moviebr** [comment]
Vou subir um commit com essa alteração, se puder testar...
