### ISSUE TITLE
Bug em comandos e determinadas funções do server com o client OTC

### ISSUE THREAD

**Issue by vine96** [moviebr/baiakthunder#20]
Bug encontrado! 

Como é o bug? 
Você não consegue executar nenhum comando que tenha uma tela de informações com barra lateral, exemplo: **!spells** ou o livro de informações de rapid respawn no templo e algumas mensagens de default também não são executadas.

Onde acontece?
Isto só acontece se você utilizar o client OTC ou Mobile.

Onde foi testado?
Eu testei em todas as versões do OTC e Mobile (que são mesma coisa praticamente).

Após utilizar o comando aparece algum erro no terminal do OTC?
Sim, este:
```
ERROR: Unhandled onTextMessage message mode 51: Bem-vindo ao {Legend Baiak}!
ERROR: Unhandled onTextMessage message mode 51: Sua última visita foi em {Sat May 29 22:05:36 2021}.
ERROR: ProtocolGame parse message exception (3321 bytes, 3302 unread, last opcode is 0x96 (150), prev opcode is 0xffffffff (-1)): InputMessage eof reached
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 860)
```

No client antigo 8.60 esse bug não acontece, não existe ele.

Creio que isso tem a ver com a função:
` player:showTextDialog(2175, table.concat(text))`

Me parece que o OTC não está preparado para receber este tipo de função ou apresentar isto em um client 8.60
Ou precise alterar alguma coisa no script ou no OTC para rodar eu não faço ideia, estou aqui pedindo socorro kkk

**Comment by moviebr** [comment]
O Baiak Thunder não tem total suporte ao OTC. Creio que em breve devo adicionar algumas features do OTC, porém não é minha prioridade no momento atualizar o projeto.
Recomendo tentar resolver e fazer um Pull Request.
