### ISSUE TITLE
Bug sistema de tasks

### ISSUE THREAD

**Issue by vine96** [moviebr/baiakthunder#21]
21:23 ADM Vine [1001]: Rotworms
21:23 Bianca: Desculpe, mas não temos essa task.

Quando você fala qualquer task que tem da lista nenhuma o NPC reconhece. 

Quando você fala: lista de task diárias
O NPC não te responde nada e verifiquei o código do NPC não tem a parte da lista de task diárias.

Mas de forma geral nada funciona neste sistema, não está sendo possível iniciar uma task.

**Comment by moviebr** [comment]
Irei revisar o sistema de Task caso eu confirme tal erro irei arrumá-lo.
Obrigado por reportar.

**Comment by vine96** [comment]
show! fico feliz pela resposta, vou ir reportando os bugs e mandando os pull requests quando possível
