### ISSUE TITLE
ERROR: COMPILING -> Visual Studio 2019

### ISSUE THREAD

**Issue by eclipse606** [moviebr/baiakthunder#23]
fiz o download e tentei compilar, aparece esses erros no iologindata.cpp

**1>------ Compilação iniciada: Projeto: theforgottenserver, Configuração: Release x64 ------
1>iologindata.cpp
1>c:\users\pateky\downloads\d\baiakthunder-master\src\iologindata.cpp(664): warning C4456: a declaração de 'it' oculta uma declaração local anterior
1>c:\users\pateky\downloads\d\baiakthunder-master\src\iologindata.cpp(658): note: consulte a declaração de 'it'
1>c:\users\pateky\downloads\d\baiakthunder-master\src\iologindata.cpp(670): error C2065: 'queue': identificador não declarado
1>c:\users\pateky\downloads\d\baiakthunder-master\src\iologindata.cpp(993): error C2660: 'IOLoginData::saveItems': função não recebe 4 argumentos
1>c:\users\pateky\downloads\d\baiakthunder-master\src\iologindata.cpp(647): note: consulte a declaração de 'IOLoginData::saveItems'
1>Projeto de compilação pronto "theforgottenserver.vcxproj" -- FALHA.
========== Compilar: 0 com êxito, 1 com falha, 0 atualizados, 0 ignorados ==========**

![logindata](https://user-images.githubusercontent.com/87678275/126241263-3ad0bb08-db59-4c4e-bdee-6b4d5a0655af.PNG)

alguém para dar um help?

**Comment by moviebr** [comment]
Try it now, I sent a possible fix.
