### ISSUE TITLE
war.lua

### ISSUE THREAD

**Issue by Tibiaone** [moviebr/baiakthunder#26]
Comando !war invite esta reconhecendo guild com apenas um nome.

O script nao consegue identificar guilds que possui mais de um nome como por exemplo: "Castle Guild, Guild Dominadores Um" entre outros.

**Comment by luanluciano93** [comment]
Se quiser, tenta usar esta: 
https://github.com/luanluciano93/ESTUDOS/blob/master/LUA/guildwars.lua
